parameters:
#    strokit_core.example.class: Strokit\CoreBundle\Example

services:
#    strokit_core.example:
#        class: %strokit_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    templating.engine.twig:
        class: Strokit\CoreBundle\Twig\TwigEngine
        arguments: ["@twig","@templating.name_parser","@templating.locator","@mobile_detect.mobile_detector"]

    strokit_mailer:
        class: Strokit\CoreBundle\Mailer\Mailer
        arguments: [@mailer, @twig]

    sonata.media.resizer.custom:
        class: Strokit\CoreBundle\Image\CustomResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]