parameters:

services:
#    strokit_core.example:
#        class: %strokit_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    templating.engine.twig:
        class: Strokit\CoreBundle\Twig\TwigEngine
        arguments: ["@twig","@templating.name_parser","@templating.locator","@mobile_detect.mobile_detector"]

    strokit_mailer:
        class: Strokit\CoreBundle\Mailer\Mailer
        arguments: [@mailer, @twig]


    strokit_breadcrumb:
        class: Strokit\CoreBundle\Menu\BreadcrumbBuilder
        arguments:
          #- [@infofaq_breadcrumb, @infomap_breadcrumb, @infopage_breadcrumb, @sonata.news.breadcrumb, @infofeedback_breadcrumb]
          - @knp_menu.factory
          - "info_elsom_homepage"

    strokit.menu.breadcrumb:
            class: Knp\Menu\MenuItem
            factory_service: strokit_breadcrumb # the menu builder service above
            factory_method: createBreadcrumbMenu # the method name to generate the menu
            arguments: ["@request"]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: breadcrumb } # The alias is used in the template