parameters:
#    info_feedback.example.class: Info\FeedbackBundle\Example

services:
#    info_feedback.example:
#        class: %info_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.feedback:
        class: Info\FeedbackBundle\Admin\FeedbackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сайт", label: "feedback.admin.label", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Info\FeedbackBundle\Entity\Feedback
            - InfoFeedbackBundle:FeedbackAdmin
        calls:
            - [ setTranslationDomain, [InfoFeedbackBundle]]

    infofeedback_breadcrumb:
        class: Info\FeedbackBundle\Menu\BreadcrumbBuilder
        arguments: ["@knp_menu.factory"]
