parameters:
#    info_feedback.example.class: Info\FeedbackBundle\Example

services:
#    info_feedback.example:
#        class: %info_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
