info_page:
    resource: "@InfoPageBundle/Resources/config/routing.yml"
    prefix:   /

info_map:
    resource: "@InfoMapBundle/Resources/config/routing.yml"
    prefix:   /

info_feedback:
    resource: "@InfoFeedbackBundle/Resources/config/routing.yml"
    prefix:   /

strokit_core:
    resource: "@StrokitCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

media_list:
    resource: '@ApplicationSonataMediaBundle/Resources/config/routing.yml'
    prefix: /media/list

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

cke_sonata_admin_browse:
    pattern: /admin/sonata/media/media/browser
    defaults: { _controller: CoopTilleulsCKEditorSonataMediaBundle:MediaAdminController:browser }
    options:
        expose: true
cke_sonata_admin_upload:
    pattern: /admin/sonata/media/media/upload
    defaults: { _controller: CoopTilleulsCKEditorSonataMediaBundle:MediaAdminController:upload }
    options:
        expose: true
