sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
        news:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 190 , quality: 95}
                big:   { width: 500 , quality: 90}

        map:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 190 , quality: 95}
                big:   { width: 500 , quality: 90}
    cdn:
        server:
            path: /cms/web/uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
    providers:
        image:
            resizer:    sonata.media.resizer.square # sonata.media.resizer.simple