sonata_news:
    title:        CMS
    link:         http://cms.org
    description:  Cool bundles on top of Symfony2
    salt:         'A7d*6sa:sadi&*5ss5dsa7'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.category

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@cms.kg
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    admin:
        post:
            class : 'Application\Sonata\NewsBundle\Admin\PostAdmin'

doctrine:
    orm:
      mappings:
        ApplicationSonataNewsBundle: ~
        SonataNewsBundle: ~