info_faq:
    pattern:  /faq/
    defaults: { _controller: InfoFAQBundle:Default:index }
    options:
        expose: true

faq_ajax_get_popup:
    pattern: /faq/popup/{id}/
    defaults: { _controller: InfoFAQBundle:Default:showFaqPopup }
    requirements:
        id:  \d+

faq_ajax_save_comment:
    pattern: /faq/save/comment/{id}/
    defaults: { _controller: InfoFAQBundle:Default:saveComment }