parameters:
#    info_faq.example.class: Info\FAQBundle\Example

services:
#    info_faq.example:
#        class: %info_faq.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.sections.faq:
        class: Info\FAQBundle\Admin\FAQSectionsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "faq.admin.content", label: "faq_sections.admin.label", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Info\FAQBundle\Entity\FaqSections
            - ~
        calls:
            - [ setTranslationDomain, [InfoFAQBundle]]
    sonata.questions_answers.faq:
            class: Info\FAQBundle\Admin\FAQQuestionsAnswersAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "faq.admin.content", label: "faq_answers_questions.admin.label", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
            arguments:
                - ~
                - Info\FAQBundle\Entity\FaqQuestionsAnswers
                - ~
            calls:
                - [ setTranslationDomain, [InfoFAQBundle]]
    sonata.comments.faq:
            class: Info\FAQBundle\Admin\FAQCommentsAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "faq.admin.content", label: "faq_comments.admin.label", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
            arguments:
                - ~
                - Info\FAQBundle\Entity\FaqComments
                - InfoFAQBundle:FAQCommentsAdmin
            calls:
                - [ setTranslationDomain, [InfoFAQBundle]]