parameters:
#    info_faq.example.class: Info\FAQBundle\Example

services:
#    info_faq.example:
#        class: %info_faq.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.faq:
        class: Info\FAQBundle\Admin\FAQAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "faq.admin.content", label: "faqsections.admin.label", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments:
            - ~
            - Info\FAQBundle\Entity\FaqSections
            - InfoFAQBundle:FAQAdmin
        calls:
            - [ setTranslationDomain, [InfoFAQBundle]]