parameters:
#    strokit_search.example.class: Strokit\SearchBundle\Example

services:
#    strokit_search.example:
#        class: %strokit_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    strokit.searcher:
        class: Strokit\SearchBundle\Searcher\Searcher
        arguments:
          - [@infoservice_searcher,@infopage_searcher,@infomap.searcher_cashout,@infomap.searcher_merchant,@infomap.searcher_terminal]