info_page:
    pattern:  /{url}.html
    defaults: { _controller: InfoPageBundle:Page:show }
    options:
        expose: true

info_service_show:
    pattern:  /service/{url}.html
    defaults: { _controller: InfoPageBundle:Service:show }

info_service_index:
    pattern:  /service/
    defaults: { _controller: InfoPageBundle:Service:index }
    options:
        expose: true