parameters:
#    info_page.example.class: Info\PageBundle\Example

services:
#    info_page.example:
#        class: %info_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.page:
        class: Info\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сайт", label: "Страница" }
        arguments:
            - ~
            - Info\PageBundle\Entity\Pages
            - ~
        calls:
            - [ setTranslationDomain, [InfoPageBundle]]


    sonata.admin.page_service:
        class: Info\PageBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Сайт", label: "Услуги" }
        arguments:
            - ~
            - Info\PageBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [InfoPageBundle]]

    infopage_breadcrumb:
        class: Info\PageBundle\Menu\BreadcrumbBuilder

    infopage_searcher:
        class: Info\PageBundle\Searcher\PageSearcher
        arguments: [@doctrine.orm.entity_manager,@router]

    infoservice_searcher:
        class: Info\PageBundle\Searcher\ServiceSearcher
        arguments: [@doctrine.orm.entity_manager,@router]